sources:
  - source/converted_ufos/Maitree-ExtraLight.ufo
  - source/converted_ufos/Maitree-Light.ufo
  - source/converted_ufos/Maitree-Regular.ufo
  - source/converted_ufos/Maitree-Medium.ufo
  - source/converted_ufos/Maitree-SemiBold.ufo
  - source/converted_ufos/Maitree-Bold.ufo
buildVariable: false
buildOTF: false
