sources:
  - src/converted_ufos/Tomorrow-Black.ufo
  - src/converted_ufos/Tomorrow-BlackItalic.ufo
  - src/converted_ufos/Tomorrow-Bold.ufo
  - src/converted_ufos/Tomorrow-BoldItalic.ufo
  - src/converted_ufos/Tomorrow-ExtraBold.ufo
  - src/converted_ufos/Tomorrow-ExtraBoldItalic.ufo
  - src/converted_ufos/Tomorrow-ExtraLight.ufo
  - src/converted_ufos/Tomorrow-ExtraLightItalic.ufo
  - src/converted_ufos/Tomorrow-Italic.ufo
  - src/converted_ufos/Tomorrow-Light.ufo
  - src/converted_ufos/Tomorrow-LightItalic.ufo
  - src/converted_ufos/Tomorrow-Medium.ufo
  - src/converted_ufos/Tomorrow-MediumItalic.ufo
  - src/converted_ufos/Tomorrow-Regular.ufo
  - src/converted_ufos/Tomorrow-SemiBold.ufo
  - src/converted_ufos/Tomorrow-SemiBoldItalic.ufo
  - src/converted_ufos/Tomorrow-Thin.ufo
  - src/converted_ufos/Tomorrow-ThinItalic.ufo
buildVariable: false
buildOTF: false
