sources:
  - "Sources/Cambay Regular/Cambay-Regular.ufo"
  - "Sources/Cambay Oblique/Cambay-Italic.ufo"
  - "Sources/Cambay Bold/Cambay-Bold.ufo"
  - "Sources/Cambay Bold Oblique/Cambay-BoldItalic.ufo"
buildVariable: false
familyName: Cambay
